# Generated by Django 5.2.8 on 2026-01-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='solution_code',
            field=models.TextField(blank=True, help_text='Pseudo-code de la solution correcte', null=True),
        ),
    ]
